### ISSUE TITLE
Any Info ? 

### ISSUE THREAD

**Issue by mahdyledurs** [dkirste/uniswap-flashloan-arbitrage#1]
hey my friend do you have any info regarding this repo ?

**Comment by dkirste** [comment]
Hi mahdyledurs,
This repository was created as part of a research paper.
The code you can find in the repo is the prototype as the artefact of this work.
It crawls the latests exchange rates of uniswap and sushiswap, sends them by using apache kafka to the evaluator which then evaluates if there are any two-currency-arbitrage opportunites for the largest 185 pairs listet on both exchanges.
If the evaluator spots any profitable arbitrage opportunity, it creates a transaction for the flash loan contract and executes the flash loan.

The prototype is able to spot arbitrage opportunities on the mainnet, but never triggered one, since frontrunners and mev will always outperform the prototype. 
On the testnet, it is perfectly working, spotting arbitrages and successfully executing flash loans.

Do you have any other questions?

**Comment by mahdyledurs** [comment]
Thank you for your fast answer! 

By now this prototype is the best looking for future projects. 
Did you try Flashbots to not deal with mev and frontrunners?
